// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

/**
 * Protobuf type {@code CandidateStatistics}
 */
public final class CandidateStatistics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CandidateStatistics)
    CandidateStatisticsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CandidateStatistics.newBuilder() to construct.
  private CandidateStatistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CandidateStatistics() {
    candidateName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CandidateStatistics();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_CandidateStatistics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_CandidateStatistics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.class, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder.class);
  }

  public static final int CANDIDATE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object candidateName_ = "";
  /**
   * <code>string candidate_name = 1;</code>
   * @return The candidateName.
   */
  @java.lang.Override
  public java.lang.String getCandidateName() {
    java.lang.Object ref = candidateName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateName_ = s;
      return s;
    }
  }
  /**
   * <code>string candidate_name = 1;</code>
   * @return The bytes for candidateName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCandidateNameBytes() {
    java.lang.Object ref = candidateName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_VOTES_FIELD_NUMBER = 2;
  private int totalVotes_ = 0;
  /**
   * <code>int32 total_votes = 2;</code>
   * @return The totalVotes.
   */
  @java.lang.Override
  public int getTotalVotes() {
    return totalVotes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidateName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, candidateName_);
    }
    if (totalVotes_ != 0) {
      output.writeInt32(2, totalVotes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidateName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, candidateName_);
    }
    if (totalVotes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalVotes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.faulttolerance.gRPC.CandidateStatistics)) {
      return super.equals(obj);
    }
    rs.raf.pds.faulttolerance.gRPC.CandidateStatistics other = (rs.raf.pds.faulttolerance.gRPC.CandidateStatistics) obj;

    if (!getCandidateName()
        .equals(other.getCandidateName())) return false;
    if (getTotalVotes()
        != other.getTotalVotes()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CANDIDATE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateName().hashCode();
    hash = (37 * hash) + TOTAL_VOTES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalVotes();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.faulttolerance.gRPC.CandidateStatistics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CandidateStatistics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CandidateStatistics)
      rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_CandidateStatistics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_CandidateStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.class, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder.class);
    }

    // Construct using rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      candidateName_ = "";
      totalVotes_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_CandidateStatistics_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics getDefaultInstanceForType() {
      return rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics build() {
      rs.raf.pds.faulttolerance.gRPC.CandidateStatistics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics buildPartial() {
      rs.raf.pds.faulttolerance.gRPC.CandidateStatistics result = new rs.raf.pds.faulttolerance.gRPC.CandidateStatistics(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.raf.pds.faulttolerance.gRPC.CandidateStatistics result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.candidateName_ = candidateName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalVotes_ = totalVotes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.faulttolerance.gRPC.CandidateStatistics) {
        return mergeFrom((rs.raf.pds.faulttolerance.gRPC.CandidateStatistics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.faulttolerance.gRPC.CandidateStatistics other) {
      if (other == rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.getDefaultInstance()) return this;
      if (!other.getCandidateName().isEmpty()) {
        candidateName_ = other.candidateName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTotalVotes() != 0) {
        setTotalVotes(other.getTotalVotes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              candidateName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              totalVotes_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object candidateName_ = "";
    /**
     * <code>string candidate_name = 1;</code>
     * @return The candidateName.
     */
    public java.lang.String getCandidateName() {
      java.lang.Object ref = candidateName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string candidate_name = 1;</code>
     * @return The bytes for candidateName.
     */
    public com.google.protobuf.ByteString
        getCandidateNameBytes() {
      java.lang.Object ref = candidateName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string candidate_name = 1;</code>
     * @param value The candidateName to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      candidateName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string candidate_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateName() {
      candidateName_ = getDefaultInstance().getCandidateName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string candidate_name = 1;</code>
     * @param value The bytes for candidateName to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      candidateName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int totalVotes_ ;
    /**
     * <code>int32 total_votes = 2;</code>
     * @return The totalVotes.
     */
    @java.lang.Override
    public int getTotalVotes() {
      return totalVotes_;
    }
    /**
     * <code>int32 total_votes = 2;</code>
     * @param value The totalVotes to set.
     * @return This builder for chaining.
     */
    public Builder setTotalVotes(int value) {

      totalVotes_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_votes = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalVotes() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalVotes_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CandidateStatistics)
  }

  // @@protoc_insertion_point(class_scope:CandidateStatistics)
  private static final rs.raf.pds.faulttolerance.gRPC.CandidateStatistics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.faulttolerance.gRPC.CandidateStatistics();
  }

  public static rs.raf.pds.faulttolerance.gRPC.CandidateStatistics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CandidateStatistics>
      PARSER = new com.google.protobuf.AbstractParser<CandidateStatistics>() {
    @java.lang.Override
    public CandidateStatistics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CandidateStatistics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CandidateStatistics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

