// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public interface CandidateStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CandidateStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string candidate_name = 1;</code>
   * @return The candidateName.
   */
  java.lang.String getCandidateName();
  /**
   * <code>string candidate_name = 1;</code>
   * @return The bytes for candidateName.
   */
  com.google.protobuf.ByteString
      getCandidateNameBytes();

  /**
   * <code>int32 total_votes = 2;</code>
   * @return The totalVotes.
   */
  int getTotalVotes();
}
