// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

/**
 * Protobuf enum {@code ElectionRequestType}
 */
public enum ElectionRequestType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUBMIT_RESULT = 0;</code>
   */
  SUBMIT_RESULT(0),
  /**
   * <code>GET_STATISTICS = 1;</code>
   */
  GET_STATISTICS(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUBMIT_RESULT = 0;</code>
   */
  public static final int SUBMIT_RESULT_VALUE = 0;
  /**
   * <code>GET_STATISTICS = 1;</code>
   */
  public static final int GET_STATISTICS_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ElectionRequestType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ElectionRequestType forNumber(int value) {
    switch (value) {
      case 0: return SUBMIT_RESULT;
      case 1: return GET_STATISTICS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ElectionRequestType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ElectionRequestType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ElectionRequestType>() {
          public ElectionRequestType findValueByNumber(int number) {
            return ElectionRequestType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ElectionRequestType[] VALUES = values();

  public static ElectionRequestType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ElectionRequestType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ElectionRequestType)
}

