// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public final class ElectionServiceOuterClass {
  private ElectionServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CandidateVote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CandidateVote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VotingResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VotingResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ElectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ElectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StatisticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StatisticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CandidateStatistics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CandidateStatistics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StatisticsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StatisticsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026election_service.proto\"6\n\rCandidateVot" +
      "e\022\026\n\016candidate_name\030\001 \001(\t\022\r\n\005votes\030\002 \001(\005" +
      "\"\356\001\n\023VotingResultRequest\022\022\n\nrequest_id\030\001" +
      " \001(\005\022\023\n\013election_id\030\002 \001(\005\022\032\n\022polling_sta" +
      "tion_id\030\003 \001(\005\022\025\n\rcontroller_id\030\004 \001(\t\022\024\n\014" +
      "total_voters\030\005 \001(\005\022\025\n\rinvalid_votes\030\006 \001(" +
      "\005\022\'\n\017candidate_votes\030\007 \003(\0132\016.CandidateVo" +
      "te\022%\n\007op_type\030\010 \001(\0162\024.ElectionRequestTyp" +
      "e\"W\n\020ElectionResponse\022\036\n\006status\030\001 \001(\0162\016." +
      "RequestStatus\022\022\n\nrequest_id\030\002 \001(\005\022\017\n\007mes" +
      "sage\030\003 \001(\t\"<\n\021StatisticsRequest\022\022\n\nreque" +
      "st_id\030\001 \001(\005\022\023\n\013election_id\030\002 \001(\005\"B\n\023Cand" +
      "idateStatistics\022\026\n\016candidate_name\030\001 \001(\t\022" +
      "\023\n\013total_votes\030\002 \001(\005\"\200\002\n\022StatisticsRespo" +
      "nse\022\036\n\006status\030\001 \001(\0162\016.RequestStatus\022\032\n\022t" +
      "urnout_percentage\030\002 \001(\002\022-\n%processed_pol" +
      "ling_stations_percentage\030\003 \001(\002\022\037\n\027repeat" +
      "_polling_stations\030\004 \001(\005\0222\n\024candidate_sta" +
      "tistics\030\005 \003(\0132\024.CandidateStatistics\022\023\n\013e" +
      "lection_id\030\006 \001(\005\022\025\n\relection_type\030\007 \001(\t*" +
      "<\n\023ElectionRequestType\022\021\n\rSUBMIT_RESULT\020" +
      "\000\022\022\n\016GET_STATISTICS\020\001*\302\001\n\rRequestStatus\022" +
      "\r\n\tSTATUS_OK\020\000\022\036\n\032UPDATE_REJECTED_NOT_LE" +
      "ADER\020\001\022\026\n\022INVALID_VOTE_COUNT\020\002\022 \n\034POLLIN" +
      "G_STATION_NEEDS_REPEAT\020\003\022\033\n\027POLLING_STAT" +
      "ION_BLOCKED\020\004\022+\n\'WITHDRAWAL_REJECT_NOT_S" +
      "UFFICIENT_AMOUNT\020\0052\204\001\n\017ElectionService\0227" +
      "\n\014SubmitResult\022\024.VotingResultRequest\032\021.E" +
      "lectionResponse\0228\n\rGetStatistics\022\022.Stati" +
      "sticsRequest\032\023.StatisticsResponseB\"\n\036rs." +
      "raf.pds.faulttolerance.gRPCP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CandidateVote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CandidateVote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CandidateVote_descriptor,
        new java.lang.String[] { "CandidateName", "Votes", });
    internal_static_VotingResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VotingResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VotingResultRequest_descriptor,
        new java.lang.String[] { "RequestId", "ElectionId", "PollingStationId", "ControllerId", "TotalVoters", "InvalidVotes", "CandidateVotes", "OpType", });
    internal_static_ElectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ElectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ElectionResponse_descriptor,
        new java.lang.String[] { "Status", "RequestId", "Message", });
    internal_static_StatisticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StatisticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StatisticsRequest_descriptor,
        new java.lang.String[] { "RequestId", "ElectionId", });
    internal_static_CandidateStatistics_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CandidateStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CandidateStatistics_descriptor,
        new java.lang.String[] { "CandidateName", "TotalVotes", });
    internal_static_StatisticsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_StatisticsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StatisticsResponse_descriptor,
        new java.lang.String[] { "Status", "TurnoutPercentage", "ProcessedPollingStationsPercentage", "RepeatPollingStations", "CandidateStatistics", "ElectionId", "ElectionType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
