// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public interface ElectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ElectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The status.
   */
  rs.raf.pds.faulttolerance.gRPC.RequestStatus getStatus();

  /**
   * <code>int32 request_id = 2;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
