// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replicated_log.proto

package rs.raf.pds.faulttolerance.gRPC;

public final class ReplicatedLog {
  private ReplicatedLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024replicated_log.proto\"6\n\010LogEntry\022\024\n\014en" +
      "tryAtIndex\030\001 \001(\004\022\024\n\014logEntryData\030\002 \001(\014\"W" +
      "\n\013LogResponse\022\032\n\006status\030\001 \001(\0162\n.LogStatu" +
      "s\022\024\n\014entryAtIndex\030\002 \001(\004\022\026\n\016lastEntryInde" +
      "x\030\003 \001(\004\"\017\n\rLeaderRequest\"4\n\nLeaderInfo\022\020" +
      "\n\010imLeader\030\001 \001(\010\022\024\n\014hostnamePort\030\002 \001(\t*?" +
      "\n\tLogStatus\022\n\n\006LOG_OK\020\000\022\014\n\010IO_ERROR\020\001\022\030\n" +
      "\024LOG_HASNT_LAST_ENTRY\020\0022j\n\024ReplicatedLog" +
      "Service\022$\n\tAppendLog\022\t.LogEntry\032\014.LogRes" +
      "ponse\022,\n\rGetLeaderInfo\022\016.LeaderRequest\032\013" +
      ".LeaderInfoB\"\n\036rs.raf.pds.faulttolerance" +
      ".gRPCP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogEntry_descriptor,
        new java.lang.String[] { "EntryAtIndex", "LogEntryData", });
    internal_static_LogResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogResponse_descriptor,
        new java.lang.String[] { "Status", "EntryAtIndex", "LastEntryIndex", });
    internal_static_LeaderRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LeaderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderRequest_descriptor,
        new java.lang.String[] { });
    internal_static_LeaderInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LeaderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderInfo_descriptor,
        new java.lang.String[] { "ImLeader", "HostnamePort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
