// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public interface StatisticsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StatisticsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 request_id = 1;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>int32 election_id = 2;</code>
   * @return The electionId.
   */
  int getElectionId();
}
