// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public interface StatisticsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StatisticsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The status.
   */
  rs.raf.pds.faulttolerance.gRPC.RequestStatus getStatus();

  /**
   * <code>float turnout_percentage = 2;</code>
   * @return The turnoutPercentage.
   */
  float getTurnoutPercentage();

  /**
   * <code>float processed_polling_stations_percentage = 3;</code>
   * @return The processedPollingStationsPercentage.
   */
  float getProcessedPollingStationsPercentage();

  /**
   * <code>int32 repeat_polling_stations = 4;</code>
   * @return The repeatPollingStations.
   */
  int getRepeatPollingStations();

  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateStatistics> 
      getCandidateStatisticsList();
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  rs.raf.pds.faulttolerance.gRPC.CandidateStatistics getCandidateStatistics(int index);
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  int getCandidateStatisticsCount();
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  java.util.List<? extends rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder> 
      getCandidateStatisticsOrBuilderList();
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder getCandidateStatisticsOrBuilder(
      int index);

  /**
   * <code>int32 election_id = 6;</code>
   * @return The electionId.
   */
  int getElectionId();

  /**
   * <code>string election_type = 7;</code>
   * @return The electionType.
   */
  java.lang.String getElectionType();
  /**
   * <code>string election_type = 7;</code>
   * @return The bytes for electionType.
   */
  com.google.protobuf.ByteString
      getElectionTypeBytes();
}
