// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

/**
 * Protobuf type {@code StatisticsResponse}
 */
public final class StatisticsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StatisticsResponse)
    StatisticsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatisticsResponse.newBuilder() to construct.
  private StatisticsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatisticsResponse() {
    status_ = 0;
    candidateStatistics_ = java.util.Collections.emptyList();
    electionType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatisticsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_StatisticsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_StatisticsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.faulttolerance.gRPC.StatisticsResponse.class, rs.raf.pds.faulttolerance.gRPC.StatisticsResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 0;
  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The status.
   */
  @java.lang.Override public rs.raf.pds.faulttolerance.gRPC.RequestStatus getStatus() {
    rs.raf.pds.faulttolerance.gRPC.RequestStatus result = rs.raf.pds.faulttolerance.gRPC.RequestStatus.forNumber(status_);
    return result == null ? rs.raf.pds.faulttolerance.gRPC.RequestStatus.UNRECOGNIZED : result;
  }

  public static final int TURNOUT_PERCENTAGE_FIELD_NUMBER = 2;
  private float turnoutPercentage_ = 0F;
  /**
   * <code>float turnout_percentage = 2;</code>
   * @return The turnoutPercentage.
   */
  @java.lang.Override
  public float getTurnoutPercentage() {
    return turnoutPercentage_;
  }

  public static final int PROCESSED_POLLING_STATIONS_PERCENTAGE_FIELD_NUMBER = 3;
  private float processedPollingStationsPercentage_ = 0F;
  /**
   * <code>float processed_polling_stations_percentage = 3;</code>
   * @return The processedPollingStationsPercentage.
   */
  @java.lang.Override
  public float getProcessedPollingStationsPercentage() {
    return processedPollingStationsPercentage_;
  }

  public static final int REPEAT_POLLING_STATIONS_FIELD_NUMBER = 4;
  private int repeatPollingStations_ = 0;
  /**
   * <code>int32 repeat_polling_stations = 4;</code>
   * @return The repeatPollingStations.
   */
  @java.lang.Override
  public int getRepeatPollingStations() {
    return repeatPollingStations_;
  }

  public static final int CANDIDATE_STATISTICS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateStatistics> candidateStatistics_;
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  @java.lang.Override
  public java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateStatistics> getCandidateStatisticsList() {
    return candidateStatistics_;
  }
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder> 
      getCandidateStatisticsOrBuilderList() {
    return candidateStatistics_;
  }
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  @java.lang.Override
  public int getCandidateStatisticsCount() {
    return candidateStatistics_.size();
  }
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  @java.lang.Override
  public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics getCandidateStatistics(int index) {
    return candidateStatistics_.get(index);
  }
  /**
   * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
   */
  @java.lang.Override
  public rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder getCandidateStatisticsOrBuilder(
      int index) {
    return candidateStatistics_.get(index);
  }

  public static final int ELECTION_ID_FIELD_NUMBER = 6;
  private int electionId_ = 0;
  /**
   * <code>int32 election_id = 6;</code>
   * @return The electionId.
   */
  @java.lang.Override
  public int getElectionId() {
    return electionId_;
  }

  public static final int ELECTION_TYPE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object electionType_ = "";
  /**
   * <code>string election_type = 7;</code>
   * @return The electionType.
   */
  @java.lang.Override
  public java.lang.String getElectionType() {
    java.lang.Object ref = electionType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      electionType_ = s;
      return s;
    }
  }
  /**
   * <code>string election_type = 7;</code>
   * @return The bytes for electionType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getElectionTypeBytes() {
    java.lang.Object ref = electionType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      electionType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != rs.raf.pds.faulttolerance.gRPC.RequestStatus.STATUS_OK.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (java.lang.Float.floatToRawIntBits(turnoutPercentage_) != 0) {
      output.writeFloat(2, turnoutPercentage_);
    }
    if (java.lang.Float.floatToRawIntBits(processedPollingStationsPercentage_) != 0) {
      output.writeFloat(3, processedPollingStationsPercentage_);
    }
    if (repeatPollingStations_ != 0) {
      output.writeInt32(4, repeatPollingStations_);
    }
    for (int i = 0; i < candidateStatistics_.size(); i++) {
      output.writeMessage(5, candidateStatistics_.get(i));
    }
    if (electionId_ != 0) {
      output.writeInt32(6, electionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(electionType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, electionType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != rs.raf.pds.faulttolerance.gRPC.RequestStatus.STATUS_OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (java.lang.Float.floatToRawIntBits(turnoutPercentage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, turnoutPercentage_);
    }
    if (java.lang.Float.floatToRawIntBits(processedPollingStationsPercentage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, processedPollingStationsPercentage_);
    }
    if (repeatPollingStations_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, repeatPollingStations_);
    }
    for (int i = 0; i < candidateStatistics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, candidateStatistics_.get(i));
    }
    if (electionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, electionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(electionType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, electionType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.faulttolerance.gRPC.StatisticsResponse)) {
      return super.equals(obj);
    }
    rs.raf.pds.faulttolerance.gRPC.StatisticsResponse other = (rs.raf.pds.faulttolerance.gRPC.StatisticsResponse) obj;

    if (status_ != other.status_) return false;
    if (java.lang.Float.floatToIntBits(getTurnoutPercentage())
        != java.lang.Float.floatToIntBits(
            other.getTurnoutPercentage())) return false;
    if (java.lang.Float.floatToIntBits(getProcessedPollingStationsPercentage())
        != java.lang.Float.floatToIntBits(
            other.getProcessedPollingStationsPercentage())) return false;
    if (getRepeatPollingStations()
        != other.getRepeatPollingStations()) return false;
    if (!getCandidateStatisticsList()
        .equals(other.getCandidateStatisticsList())) return false;
    if (getElectionId()
        != other.getElectionId()) return false;
    if (!getElectionType()
        .equals(other.getElectionType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + TURNOUT_PERCENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTurnoutPercentage());
    hash = (37 * hash) + PROCESSED_POLLING_STATIONS_PERCENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getProcessedPollingStationsPercentage());
    hash = (37 * hash) + REPEAT_POLLING_STATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getRepeatPollingStations();
    if (getCandidateStatisticsCount() > 0) {
      hash = (37 * hash) + CANDIDATE_STATISTICS_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateStatisticsList().hashCode();
    }
    hash = (37 * hash) + ELECTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getElectionId();
    hash = (37 * hash) + ELECTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getElectionType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.faulttolerance.gRPC.StatisticsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StatisticsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StatisticsResponse)
      rs.raf.pds.faulttolerance.gRPC.StatisticsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_StatisticsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_StatisticsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.faulttolerance.gRPC.StatisticsResponse.class, rs.raf.pds.faulttolerance.gRPC.StatisticsResponse.Builder.class);
    }

    // Construct using rs.raf.pds.faulttolerance.gRPC.StatisticsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      turnoutPercentage_ = 0F;
      processedPollingStationsPercentage_ = 0F;
      repeatPollingStations_ = 0;
      if (candidateStatisticsBuilder_ == null) {
        candidateStatistics_ = java.util.Collections.emptyList();
      } else {
        candidateStatistics_ = null;
        candidateStatisticsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      electionId_ = 0;
      electionType_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_StatisticsResponse_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.StatisticsResponse getDefaultInstanceForType() {
      return rs.raf.pds.faulttolerance.gRPC.StatisticsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.StatisticsResponse build() {
      rs.raf.pds.faulttolerance.gRPC.StatisticsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.StatisticsResponse buildPartial() {
      rs.raf.pds.faulttolerance.gRPC.StatisticsResponse result = new rs.raf.pds.faulttolerance.gRPC.StatisticsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(rs.raf.pds.faulttolerance.gRPC.StatisticsResponse result) {
      if (candidateStatisticsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          candidateStatistics_ = java.util.Collections.unmodifiableList(candidateStatistics_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.candidateStatistics_ = candidateStatistics_;
      } else {
        result.candidateStatistics_ = candidateStatisticsBuilder_.build();
      }
    }

    private void buildPartial0(rs.raf.pds.faulttolerance.gRPC.StatisticsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.turnoutPercentage_ = turnoutPercentage_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.processedPollingStationsPercentage_ = processedPollingStationsPercentage_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.repeatPollingStations_ = repeatPollingStations_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.electionId_ = electionId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.electionType_ = electionType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.faulttolerance.gRPC.StatisticsResponse) {
        return mergeFrom((rs.raf.pds.faulttolerance.gRPC.StatisticsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.faulttolerance.gRPC.StatisticsResponse other) {
      if (other == rs.raf.pds.faulttolerance.gRPC.StatisticsResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getTurnoutPercentage() != 0F) {
        setTurnoutPercentage(other.getTurnoutPercentage());
      }
      if (other.getProcessedPollingStationsPercentage() != 0F) {
        setProcessedPollingStationsPercentage(other.getProcessedPollingStationsPercentage());
      }
      if (other.getRepeatPollingStations() != 0) {
        setRepeatPollingStations(other.getRepeatPollingStations());
      }
      if (candidateStatisticsBuilder_ == null) {
        if (!other.candidateStatistics_.isEmpty()) {
          if (candidateStatistics_.isEmpty()) {
            candidateStatistics_ = other.candidateStatistics_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCandidateStatisticsIsMutable();
            candidateStatistics_.addAll(other.candidateStatistics_);
          }
          onChanged();
        }
      } else {
        if (!other.candidateStatistics_.isEmpty()) {
          if (candidateStatisticsBuilder_.isEmpty()) {
            candidateStatisticsBuilder_.dispose();
            candidateStatisticsBuilder_ = null;
            candidateStatistics_ = other.candidateStatistics_;
            bitField0_ = (bitField0_ & ~0x00000010);
            candidateStatisticsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCandidateStatisticsFieldBuilder() : null;
          } else {
            candidateStatisticsBuilder_.addAllMessages(other.candidateStatistics_);
          }
        }
      }
      if (other.getElectionId() != 0) {
        setElectionId(other.getElectionId());
      }
      if (!other.getElectionType().isEmpty()) {
        electionType_ = other.electionType_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              turnoutPercentage_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              processedPollingStationsPercentage_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 32: {
              repeatPollingStations_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              rs.raf.pds.faulttolerance.gRPC.CandidateStatistics m =
                  input.readMessage(
                      rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.parser(),
                      extensionRegistry);
              if (candidateStatisticsBuilder_ == null) {
                ensureCandidateStatisticsIsMutable();
                candidateStatistics_.add(m);
              } else {
                candidateStatisticsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 48: {
              electionId_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              electionType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>.RequestStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.RequestStatus status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.RequestStatus status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.RequestStatus getStatus() {
      rs.raf.pds.faulttolerance.gRPC.RequestStatus result = rs.raf.pds.faulttolerance.gRPC.RequestStatus.forNumber(status_);
      return result == null ? rs.raf.pds.faulttolerance.gRPC.RequestStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.RequestStatus status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(rs.raf.pds.faulttolerance.gRPC.RequestStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.RequestStatus status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private float turnoutPercentage_ ;
    /**
     * <code>float turnout_percentage = 2;</code>
     * @return The turnoutPercentage.
     */
    @java.lang.Override
    public float getTurnoutPercentage() {
      return turnoutPercentage_;
    }
    /**
     * <code>float turnout_percentage = 2;</code>
     * @param value The turnoutPercentage to set.
     * @return This builder for chaining.
     */
    public Builder setTurnoutPercentage(float value) {

      turnoutPercentage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float turnout_percentage = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTurnoutPercentage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      turnoutPercentage_ = 0F;
      onChanged();
      return this;
    }

    private float processedPollingStationsPercentage_ ;
    /**
     * <code>float processed_polling_stations_percentage = 3;</code>
     * @return The processedPollingStationsPercentage.
     */
    @java.lang.Override
    public float getProcessedPollingStationsPercentage() {
      return processedPollingStationsPercentage_;
    }
    /**
     * <code>float processed_polling_stations_percentage = 3;</code>
     * @param value The processedPollingStationsPercentage to set.
     * @return This builder for chaining.
     */
    public Builder setProcessedPollingStationsPercentage(float value) {

      processedPollingStationsPercentage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float processed_polling_stations_percentage = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessedPollingStationsPercentage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      processedPollingStationsPercentage_ = 0F;
      onChanged();
      return this;
    }

    private int repeatPollingStations_ ;
    /**
     * <code>int32 repeat_polling_stations = 4;</code>
     * @return The repeatPollingStations.
     */
    @java.lang.Override
    public int getRepeatPollingStations() {
      return repeatPollingStations_;
    }
    /**
     * <code>int32 repeat_polling_stations = 4;</code>
     * @param value The repeatPollingStations to set.
     * @return This builder for chaining.
     */
    public Builder setRepeatPollingStations(int value) {

      repeatPollingStations_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 repeat_polling_stations = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepeatPollingStations() {
      bitField0_ = (bitField0_ & ~0x00000008);
      repeatPollingStations_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateStatistics> candidateStatistics_ =
      java.util.Collections.emptyList();
    private void ensureCandidateStatisticsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        candidateStatistics_ = new java.util.ArrayList<rs.raf.pds.faulttolerance.gRPC.CandidateStatistics>(candidateStatistics_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.faulttolerance.gRPC.CandidateStatistics, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder, rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder> candidateStatisticsBuilder_;

    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateStatistics> getCandidateStatisticsList() {
      if (candidateStatisticsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(candidateStatistics_);
      } else {
        return candidateStatisticsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public int getCandidateStatisticsCount() {
      if (candidateStatisticsBuilder_ == null) {
        return candidateStatistics_.size();
      } else {
        return candidateStatisticsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics getCandidateStatistics(int index) {
      if (candidateStatisticsBuilder_ == null) {
        return candidateStatistics_.get(index);
      } else {
        return candidateStatisticsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder setCandidateStatistics(
        int index, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics value) {
      if (candidateStatisticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateStatisticsIsMutable();
        candidateStatistics_.set(index, value);
        onChanged();
      } else {
        candidateStatisticsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder setCandidateStatistics(
        int index, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder builderForValue) {
      if (candidateStatisticsBuilder_ == null) {
        ensureCandidateStatisticsIsMutable();
        candidateStatistics_.set(index, builderForValue.build());
        onChanged();
      } else {
        candidateStatisticsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder addCandidateStatistics(rs.raf.pds.faulttolerance.gRPC.CandidateStatistics value) {
      if (candidateStatisticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateStatisticsIsMutable();
        candidateStatistics_.add(value);
        onChanged();
      } else {
        candidateStatisticsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder addCandidateStatistics(
        int index, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics value) {
      if (candidateStatisticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateStatisticsIsMutable();
        candidateStatistics_.add(index, value);
        onChanged();
      } else {
        candidateStatisticsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder addCandidateStatistics(
        rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder builderForValue) {
      if (candidateStatisticsBuilder_ == null) {
        ensureCandidateStatisticsIsMutable();
        candidateStatistics_.add(builderForValue.build());
        onChanged();
      } else {
        candidateStatisticsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder addCandidateStatistics(
        int index, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder builderForValue) {
      if (candidateStatisticsBuilder_ == null) {
        ensureCandidateStatisticsIsMutable();
        candidateStatistics_.add(index, builderForValue.build());
        onChanged();
      } else {
        candidateStatisticsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder addAllCandidateStatistics(
        java.lang.Iterable<? extends rs.raf.pds.faulttolerance.gRPC.CandidateStatistics> values) {
      if (candidateStatisticsBuilder_ == null) {
        ensureCandidateStatisticsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, candidateStatistics_);
        onChanged();
      } else {
        candidateStatisticsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder clearCandidateStatistics() {
      if (candidateStatisticsBuilder_ == null) {
        candidateStatistics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        candidateStatisticsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public Builder removeCandidateStatistics(int index) {
      if (candidateStatisticsBuilder_ == null) {
        ensureCandidateStatisticsIsMutable();
        candidateStatistics_.remove(index);
        onChanged();
      } else {
        candidateStatisticsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder getCandidateStatisticsBuilder(
        int index) {
      return getCandidateStatisticsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder getCandidateStatisticsOrBuilder(
        int index) {
      if (candidateStatisticsBuilder_ == null) {
        return candidateStatistics_.get(index);  } else {
        return candidateStatisticsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public java.util.List<? extends rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder> 
         getCandidateStatisticsOrBuilderList() {
      if (candidateStatisticsBuilder_ != null) {
        return candidateStatisticsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(candidateStatistics_);
      }
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder addCandidateStatisticsBuilder() {
      return getCandidateStatisticsFieldBuilder().addBuilder(
          rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.getDefaultInstance());
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder addCandidateStatisticsBuilder(
        int index) {
      return getCandidateStatisticsFieldBuilder().addBuilder(
          index, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.getDefaultInstance());
    }
    /**
     * <code>repeated .CandidateStatistics candidate_statistics = 5;</code>
     */
    public java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder> 
         getCandidateStatisticsBuilderList() {
      return getCandidateStatisticsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.faulttolerance.gRPC.CandidateStatistics, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder, rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder> 
        getCandidateStatisticsFieldBuilder() {
      if (candidateStatisticsBuilder_ == null) {
        candidateStatisticsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            rs.raf.pds.faulttolerance.gRPC.CandidateStatistics, rs.raf.pds.faulttolerance.gRPC.CandidateStatistics.Builder, rs.raf.pds.faulttolerance.gRPC.CandidateStatisticsOrBuilder>(
                candidateStatistics_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        candidateStatistics_ = null;
      }
      return candidateStatisticsBuilder_;
    }

    private int electionId_ ;
    /**
     * <code>int32 election_id = 6;</code>
     * @return The electionId.
     */
    @java.lang.Override
    public int getElectionId() {
      return electionId_;
    }
    /**
     * <code>int32 election_id = 6;</code>
     * @param value The electionId to set.
     * @return This builder for chaining.
     */
    public Builder setElectionId(int value) {

      electionId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 election_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearElectionId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      electionId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object electionType_ = "";
    /**
     * <code>string election_type = 7;</code>
     * @return The electionType.
     */
    public java.lang.String getElectionType() {
      java.lang.Object ref = electionType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        electionType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string election_type = 7;</code>
     * @return The bytes for electionType.
     */
    public com.google.protobuf.ByteString
        getElectionTypeBytes() {
      java.lang.Object ref = electionType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        electionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string election_type = 7;</code>
     * @param value The electionType to set.
     * @return This builder for chaining.
     */
    public Builder setElectionType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      electionType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string election_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearElectionType() {
      electionType_ = getDefaultInstance().getElectionType();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string election_type = 7;</code>
     * @param value The bytes for electionType to set.
     * @return This builder for chaining.
     */
    public Builder setElectionTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      electionType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StatisticsResponse)
  }

  // @@protoc_insertion_point(class_scope:StatisticsResponse)
  private static final rs.raf.pds.faulttolerance.gRPC.StatisticsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.faulttolerance.gRPC.StatisticsResponse();
  }

  public static rs.raf.pds.faulttolerance.gRPC.StatisticsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatisticsResponse>
      PARSER = new com.google.protobuf.AbstractParser<StatisticsResponse>() {
    @java.lang.Override
    public StatisticsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StatisticsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatisticsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.faulttolerance.gRPC.StatisticsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

