// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public interface VotingResultRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VotingResultRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 request_id = 1;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>int32 election_id = 2;</code>
   * @return The electionId.
   */
  int getElectionId();

  /**
   * <code>int32 polling_station_id = 3;</code>
   * @return The pollingStationId.
   */
  int getPollingStationId();

  /**
   * <code>string controller_id = 4;</code>
   * @return The controllerId.
   */
  java.lang.String getControllerId();
  /**
   * <code>string controller_id = 4;</code>
   * @return The bytes for controllerId.
   */
  com.google.protobuf.ByteString
      getControllerIdBytes();

  /**
   * <code>int32 total_voters = 5;</code>
   * @return The totalVoters.
   */
  int getTotalVoters();

  /**
   * <code>int32 invalid_votes = 6;</code>
   * @return The invalidVotes.
   */
  int getInvalidVotes();

  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateVote> 
      getCandidateVotesList();
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  rs.raf.pds.faulttolerance.gRPC.CandidateVote getCandidateVotes(int index);
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  int getCandidateVotesCount();
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  java.util.List<? extends rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder> 
      getCandidateVotesOrBuilderList();
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder getCandidateVotesOrBuilder(
      int index);

  /**
   * <code>.ElectionRequestType op_type = 8;</code>
   * @return The enum numeric value on the wire for opType.
   */
  int getOpTypeValue();
  /**
   * <code>.ElectionRequestType op_type = 8;</code>
   * @return The opType.
   */
  rs.raf.pds.faulttolerance.gRPC.ElectionRequestType getOpType();
}
