// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election_service.proto

package rs.raf.pds.faulttolerance.gRPC;

/**
 * Protobuf type {@code VotingResultRequest}
 */
public final class VotingResultRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VotingResultRequest)
    VotingResultRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VotingResultRequest.newBuilder() to construct.
  private VotingResultRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VotingResultRequest() {
    controllerId_ = "";
    candidateVotes_ = java.util.Collections.emptyList();
    opType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VotingResultRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_VotingResultRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_VotingResultRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.faulttolerance.gRPC.VotingResultRequest.class, rs.raf.pds.faulttolerance.gRPC.VotingResultRequest.Builder.class);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private int requestId_ = 0;
  /**
   * <code>int32 request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public int getRequestId() {
    return requestId_;
  }

  public static final int ELECTION_ID_FIELD_NUMBER = 2;
  private int electionId_ = 0;
  /**
   * <code>int32 election_id = 2;</code>
   * @return The electionId.
   */
  @java.lang.Override
  public int getElectionId() {
    return electionId_;
  }

  public static final int POLLING_STATION_ID_FIELD_NUMBER = 3;
  private int pollingStationId_ = 0;
  /**
   * <code>int32 polling_station_id = 3;</code>
   * @return The pollingStationId.
   */
  @java.lang.Override
  public int getPollingStationId() {
    return pollingStationId_;
  }

  public static final int CONTROLLER_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object controllerId_ = "";
  /**
   * <code>string controller_id = 4;</code>
   * @return The controllerId.
   */
  @java.lang.Override
  public java.lang.String getControllerId() {
    java.lang.Object ref = controllerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      controllerId_ = s;
      return s;
    }
  }
  /**
   * <code>string controller_id = 4;</code>
   * @return The bytes for controllerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getControllerIdBytes() {
    java.lang.Object ref = controllerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      controllerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_VOTERS_FIELD_NUMBER = 5;
  private int totalVoters_ = 0;
  /**
   * <code>int32 total_voters = 5;</code>
   * @return The totalVoters.
   */
  @java.lang.Override
  public int getTotalVoters() {
    return totalVoters_;
  }

  public static final int INVALID_VOTES_FIELD_NUMBER = 6;
  private int invalidVotes_ = 0;
  /**
   * <code>int32 invalid_votes = 6;</code>
   * @return The invalidVotes.
   */
  @java.lang.Override
  public int getInvalidVotes() {
    return invalidVotes_;
  }

  public static final int CANDIDATE_VOTES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateVote> candidateVotes_;
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  @java.lang.Override
  public java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateVote> getCandidateVotesList() {
    return candidateVotes_;
  }
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder> 
      getCandidateVotesOrBuilderList() {
    return candidateVotes_;
  }
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  @java.lang.Override
  public int getCandidateVotesCount() {
    return candidateVotes_.size();
  }
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  @java.lang.Override
  public rs.raf.pds.faulttolerance.gRPC.CandidateVote getCandidateVotes(int index) {
    return candidateVotes_.get(index);
  }
  /**
   * <code>repeated .CandidateVote candidate_votes = 7;</code>
   */
  @java.lang.Override
  public rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder getCandidateVotesOrBuilder(
      int index) {
    return candidateVotes_.get(index);
  }

  public static final int OP_TYPE_FIELD_NUMBER = 8;
  private int opType_ = 0;
  /**
   * <code>.ElectionRequestType op_type = 8;</code>
   * @return The enum numeric value on the wire for opType.
   */
  @java.lang.Override public int getOpTypeValue() {
    return opType_;
  }
  /**
   * <code>.ElectionRequestType op_type = 8;</code>
   * @return The opType.
   */
  @java.lang.Override public rs.raf.pds.faulttolerance.gRPC.ElectionRequestType getOpType() {
    rs.raf.pds.faulttolerance.gRPC.ElectionRequestType result = rs.raf.pds.faulttolerance.gRPC.ElectionRequestType.forNumber(opType_);
    return result == null ? rs.raf.pds.faulttolerance.gRPC.ElectionRequestType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestId_ != 0) {
      output.writeInt32(1, requestId_);
    }
    if (electionId_ != 0) {
      output.writeInt32(2, electionId_);
    }
    if (pollingStationId_ != 0) {
      output.writeInt32(3, pollingStationId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(controllerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, controllerId_);
    }
    if (totalVoters_ != 0) {
      output.writeInt32(5, totalVoters_);
    }
    if (invalidVotes_ != 0) {
      output.writeInt32(6, invalidVotes_);
    }
    for (int i = 0; i < candidateVotes_.size(); i++) {
      output.writeMessage(7, candidateVotes_.get(i));
    }
    if (opType_ != rs.raf.pds.faulttolerance.gRPC.ElectionRequestType.SUBMIT_RESULT.getNumber()) {
      output.writeEnum(8, opType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, requestId_);
    }
    if (electionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, electionId_);
    }
    if (pollingStationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, pollingStationId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(controllerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, controllerId_);
    }
    if (totalVoters_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, totalVoters_);
    }
    if (invalidVotes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, invalidVotes_);
    }
    for (int i = 0; i < candidateVotes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, candidateVotes_.get(i));
    }
    if (opType_ != rs.raf.pds.faulttolerance.gRPC.ElectionRequestType.SUBMIT_RESULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, opType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.faulttolerance.gRPC.VotingResultRequest)) {
      return super.equals(obj);
    }
    rs.raf.pds.faulttolerance.gRPC.VotingResultRequest other = (rs.raf.pds.faulttolerance.gRPC.VotingResultRequest) obj;

    if (getRequestId()
        != other.getRequestId()) return false;
    if (getElectionId()
        != other.getElectionId()) return false;
    if (getPollingStationId()
        != other.getPollingStationId()) return false;
    if (!getControllerId()
        .equals(other.getControllerId())) return false;
    if (getTotalVoters()
        != other.getTotalVoters()) return false;
    if (getInvalidVotes()
        != other.getInvalidVotes()) return false;
    if (!getCandidateVotesList()
        .equals(other.getCandidateVotesList())) return false;
    if (opType_ != other.opType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId();
    hash = (37 * hash) + ELECTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getElectionId();
    hash = (37 * hash) + POLLING_STATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPollingStationId();
    hash = (37 * hash) + CONTROLLER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getControllerId().hashCode();
    hash = (37 * hash) + TOTAL_VOTERS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalVoters();
    hash = (37 * hash) + INVALID_VOTES_FIELD_NUMBER;
    hash = (53 * hash) + getInvalidVotes();
    if (getCandidateVotesCount() > 0) {
      hash = (37 * hash) + CANDIDATE_VOTES_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateVotesList().hashCode();
    }
    hash = (37 * hash) + OP_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + opType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.faulttolerance.gRPC.VotingResultRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VotingResultRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VotingResultRequest)
      rs.raf.pds.faulttolerance.gRPC.VotingResultRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_VotingResultRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_VotingResultRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.faulttolerance.gRPC.VotingResultRequest.class, rs.raf.pds.faulttolerance.gRPC.VotingResultRequest.Builder.class);
    }

    // Construct using rs.raf.pds.faulttolerance.gRPC.VotingResultRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = 0;
      electionId_ = 0;
      pollingStationId_ = 0;
      controllerId_ = "";
      totalVoters_ = 0;
      invalidVotes_ = 0;
      if (candidateVotesBuilder_ == null) {
        candidateVotes_ = java.util.Collections.emptyList();
      } else {
        candidateVotes_ = null;
        candidateVotesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      opType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.faulttolerance.gRPC.ElectionServiceOuterClass.internal_static_VotingResultRequest_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.VotingResultRequest getDefaultInstanceForType() {
      return rs.raf.pds.faulttolerance.gRPC.VotingResultRequest.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.VotingResultRequest build() {
      rs.raf.pds.faulttolerance.gRPC.VotingResultRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.VotingResultRequest buildPartial() {
      rs.raf.pds.faulttolerance.gRPC.VotingResultRequest result = new rs.raf.pds.faulttolerance.gRPC.VotingResultRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(rs.raf.pds.faulttolerance.gRPC.VotingResultRequest result) {
      if (candidateVotesBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          candidateVotes_ = java.util.Collections.unmodifiableList(candidateVotes_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.candidateVotes_ = candidateVotes_;
      } else {
        result.candidateVotes_ = candidateVotesBuilder_.build();
      }
    }

    private void buildPartial0(rs.raf.pds.faulttolerance.gRPC.VotingResultRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.electionId_ = electionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pollingStationId_ = pollingStationId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.controllerId_ = controllerId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.totalVoters_ = totalVoters_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.invalidVotes_ = invalidVotes_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.opType_ = opType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.faulttolerance.gRPC.VotingResultRequest) {
        return mergeFrom((rs.raf.pds.faulttolerance.gRPC.VotingResultRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.faulttolerance.gRPC.VotingResultRequest other) {
      if (other == rs.raf.pds.faulttolerance.gRPC.VotingResultRequest.getDefaultInstance()) return this;
      if (other.getRequestId() != 0) {
        setRequestId(other.getRequestId());
      }
      if (other.getElectionId() != 0) {
        setElectionId(other.getElectionId());
      }
      if (other.getPollingStationId() != 0) {
        setPollingStationId(other.getPollingStationId());
      }
      if (!other.getControllerId().isEmpty()) {
        controllerId_ = other.controllerId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getTotalVoters() != 0) {
        setTotalVoters(other.getTotalVoters());
      }
      if (other.getInvalidVotes() != 0) {
        setInvalidVotes(other.getInvalidVotes());
      }
      if (candidateVotesBuilder_ == null) {
        if (!other.candidateVotes_.isEmpty()) {
          if (candidateVotes_.isEmpty()) {
            candidateVotes_ = other.candidateVotes_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureCandidateVotesIsMutable();
            candidateVotes_.addAll(other.candidateVotes_);
          }
          onChanged();
        }
      } else {
        if (!other.candidateVotes_.isEmpty()) {
          if (candidateVotesBuilder_.isEmpty()) {
            candidateVotesBuilder_.dispose();
            candidateVotesBuilder_ = null;
            candidateVotes_ = other.candidateVotes_;
            bitField0_ = (bitField0_ & ~0x00000040);
            candidateVotesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCandidateVotesFieldBuilder() : null;
          } else {
            candidateVotesBuilder_.addAllMessages(other.candidateVotes_);
          }
        }
      }
      if (other.opType_ != 0) {
        setOpTypeValue(other.getOpTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              requestId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              electionId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              pollingStationId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              controllerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              totalVoters_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              invalidVotes_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              rs.raf.pds.faulttolerance.gRPC.CandidateVote m =
                  input.readMessage(
                      rs.raf.pds.faulttolerance.gRPC.CandidateVote.parser(),
                      extensionRegistry);
              if (candidateVotesBuilder_ == null) {
                ensureCandidateVotesIsMutable();
                candidateVotes_.add(m);
              } else {
                candidateVotesBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 64: {
              opType_ = input.readEnum();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int requestId_ ;
    /**
     * <code>int32 request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }
    /**
     * <code>int32 request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(int value) {

      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestId_ = 0;
      onChanged();
      return this;
    }

    private int electionId_ ;
    /**
     * <code>int32 election_id = 2;</code>
     * @return The electionId.
     */
    @java.lang.Override
    public int getElectionId() {
      return electionId_;
    }
    /**
     * <code>int32 election_id = 2;</code>
     * @param value The electionId to set.
     * @return This builder for chaining.
     */
    public Builder setElectionId(int value) {

      electionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 election_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearElectionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      electionId_ = 0;
      onChanged();
      return this;
    }

    private int pollingStationId_ ;
    /**
     * <code>int32 polling_station_id = 3;</code>
     * @return The pollingStationId.
     */
    @java.lang.Override
    public int getPollingStationId() {
      return pollingStationId_;
    }
    /**
     * <code>int32 polling_station_id = 3;</code>
     * @param value The pollingStationId to set.
     * @return This builder for chaining.
     */
    public Builder setPollingStationId(int value) {

      pollingStationId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 polling_station_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPollingStationId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pollingStationId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object controllerId_ = "";
    /**
     * <code>string controller_id = 4;</code>
     * @return The controllerId.
     */
    public java.lang.String getControllerId() {
      java.lang.Object ref = controllerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        controllerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string controller_id = 4;</code>
     * @return The bytes for controllerId.
     */
    public com.google.protobuf.ByteString
        getControllerIdBytes() {
      java.lang.Object ref = controllerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        controllerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string controller_id = 4;</code>
     * @param value The controllerId to set.
     * @return This builder for chaining.
     */
    public Builder setControllerId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      controllerId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string controller_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearControllerId() {
      controllerId_ = getDefaultInstance().getControllerId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string controller_id = 4;</code>
     * @param value The bytes for controllerId to set.
     * @return This builder for chaining.
     */
    public Builder setControllerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      controllerId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int totalVoters_ ;
    /**
     * <code>int32 total_voters = 5;</code>
     * @return The totalVoters.
     */
    @java.lang.Override
    public int getTotalVoters() {
      return totalVoters_;
    }
    /**
     * <code>int32 total_voters = 5;</code>
     * @param value The totalVoters to set.
     * @return This builder for chaining.
     */
    public Builder setTotalVoters(int value) {

      totalVoters_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_voters = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalVoters() {
      bitField0_ = (bitField0_ & ~0x00000010);
      totalVoters_ = 0;
      onChanged();
      return this;
    }

    private int invalidVotes_ ;
    /**
     * <code>int32 invalid_votes = 6;</code>
     * @return The invalidVotes.
     */
    @java.lang.Override
    public int getInvalidVotes() {
      return invalidVotes_;
    }
    /**
     * <code>int32 invalid_votes = 6;</code>
     * @param value The invalidVotes to set.
     * @return This builder for chaining.
     */
    public Builder setInvalidVotes(int value) {

      invalidVotes_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 invalid_votes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvalidVotes() {
      bitField0_ = (bitField0_ & ~0x00000020);
      invalidVotes_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateVote> candidateVotes_ =
      java.util.Collections.emptyList();
    private void ensureCandidateVotesIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        candidateVotes_ = new java.util.ArrayList<rs.raf.pds.faulttolerance.gRPC.CandidateVote>(candidateVotes_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.faulttolerance.gRPC.CandidateVote, rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder, rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder> candidateVotesBuilder_;

    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateVote> getCandidateVotesList() {
      if (candidateVotesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(candidateVotes_);
      } else {
        return candidateVotesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public int getCandidateVotesCount() {
      if (candidateVotesBuilder_ == null) {
        return candidateVotes_.size();
      } else {
        return candidateVotesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateVote getCandidateVotes(int index) {
      if (candidateVotesBuilder_ == null) {
        return candidateVotes_.get(index);
      } else {
        return candidateVotesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder setCandidateVotes(
        int index, rs.raf.pds.faulttolerance.gRPC.CandidateVote value) {
      if (candidateVotesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateVotesIsMutable();
        candidateVotes_.set(index, value);
        onChanged();
      } else {
        candidateVotesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder setCandidateVotes(
        int index, rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder builderForValue) {
      if (candidateVotesBuilder_ == null) {
        ensureCandidateVotesIsMutable();
        candidateVotes_.set(index, builderForValue.build());
        onChanged();
      } else {
        candidateVotesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder addCandidateVotes(rs.raf.pds.faulttolerance.gRPC.CandidateVote value) {
      if (candidateVotesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateVotesIsMutable();
        candidateVotes_.add(value);
        onChanged();
      } else {
        candidateVotesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder addCandidateVotes(
        int index, rs.raf.pds.faulttolerance.gRPC.CandidateVote value) {
      if (candidateVotesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateVotesIsMutable();
        candidateVotes_.add(index, value);
        onChanged();
      } else {
        candidateVotesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder addCandidateVotes(
        rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder builderForValue) {
      if (candidateVotesBuilder_ == null) {
        ensureCandidateVotesIsMutable();
        candidateVotes_.add(builderForValue.build());
        onChanged();
      } else {
        candidateVotesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder addCandidateVotes(
        int index, rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder builderForValue) {
      if (candidateVotesBuilder_ == null) {
        ensureCandidateVotesIsMutable();
        candidateVotes_.add(index, builderForValue.build());
        onChanged();
      } else {
        candidateVotesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder addAllCandidateVotes(
        java.lang.Iterable<? extends rs.raf.pds.faulttolerance.gRPC.CandidateVote> values) {
      if (candidateVotesBuilder_ == null) {
        ensureCandidateVotesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, candidateVotes_);
        onChanged();
      } else {
        candidateVotesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder clearCandidateVotes() {
      if (candidateVotesBuilder_ == null) {
        candidateVotes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        candidateVotesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public Builder removeCandidateVotes(int index) {
      if (candidateVotesBuilder_ == null) {
        ensureCandidateVotesIsMutable();
        candidateVotes_.remove(index);
        onChanged();
      } else {
        candidateVotesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder getCandidateVotesBuilder(
        int index) {
      return getCandidateVotesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder getCandidateVotesOrBuilder(
        int index) {
      if (candidateVotesBuilder_ == null) {
        return candidateVotes_.get(index);  } else {
        return candidateVotesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public java.util.List<? extends rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder> 
         getCandidateVotesOrBuilderList() {
      if (candidateVotesBuilder_ != null) {
        return candidateVotesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(candidateVotes_);
      }
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder addCandidateVotesBuilder() {
      return getCandidateVotesFieldBuilder().addBuilder(
          rs.raf.pds.faulttolerance.gRPC.CandidateVote.getDefaultInstance());
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder addCandidateVotesBuilder(
        int index) {
      return getCandidateVotesFieldBuilder().addBuilder(
          index, rs.raf.pds.faulttolerance.gRPC.CandidateVote.getDefaultInstance());
    }
    /**
     * <code>repeated .CandidateVote candidate_votes = 7;</code>
     */
    public java.util.List<rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder> 
         getCandidateVotesBuilderList() {
      return getCandidateVotesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.faulttolerance.gRPC.CandidateVote, rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder, rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder> 
        getCandidateVotesFieldBuilder() {
      if (candidateVotesBuilder_ == null) {
        candidateVotesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            rs.raf.pds.faulttolerance.gRPC.CandidateVote, rs.raf.pds.faulttolerance.gRPC.CandidateVote.Builder, rs.raf.pds.faulttolerance.gRPC.CandidateVoteOrBuilder>(
                candidateVotes_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        candidateVotes_ = null;
      }
      return candidateVotesBuilder_;
    }

    private int opType_ = 0;
    /**
     * <code>.ElectionRequestType op_type = 8;</code>
     * @return The enum numeric value on the wire for opType.
     */
    @java.lang.Override public int getOpTypeValue() {
      return opType_;
    }
    /**
     * <code>.ElectionRequestType op_type = 8;</code>
     * @param value The enum numeric value on the wire for opType to set.
     * @return This builder for chaining.
     */
    public Builder setOpTypeValue(int value) {
      opType_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.ElectionRequestType op_type = 8;</code>
     * @return The opType.
     */
    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.ElectionRequestType getOpType() {
      rs.raf.pds.faulttolerance.gRPC.ElectionRequestType result = rs.raf.pds.faulttolerance.gRPC.ElectionRequestType.forNumber(opType_);
      return result == null ? rs.raf.pds.faulttolerance.gRPC.ElectionRequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ElectionRequestType op_type = 8;</code>
     * @param value The opType to set.
     * @return This builder for chaining.
     */
    public Builder setOpType(rs.raf.pds.faulttolerance.gRPC.ElectionRequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      opType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ElectionRequestType op_type = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpType() {
      bitField0_ = (bitField0_ & ~0x00000080);
      opType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VotingResultRequest)
  }

  // @@protoc_insertion_point(class_scope:VotingResultRequest)
  private static final rs.raf.pds.faulttolerance.gRPC.VotingResultRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.faulttolerance.gRPC.VotingResultRequest();
  }

  public static rs.raf.pds.faulttolerance.gRPC.VotingResultRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VotingResultRequest>
      PARSER = new com.google.protobuf.AbstractParser<VotingResultRequest>() {
    @java.lang.Override
    public VotingResultRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VotingResultRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VotingResultRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.faulttolerance.gRPC.VotingResultRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

